### ISSUE TITLE
Regarding the discrete time ground truth issue: 

### ISSUE THREAD

**Issue by bumblebee15138** [mcdviral/mcdviral.github.io#1]
I have downloaded the files provided in the Survey-grade prior map, but the pose_inW.csv I received only contains a few dozen timestamps of discrete time ground truth. I would like to inquire if I might have downloaded the wrong file. If so, could you please provide me with the correct download location? Thank you.

**Comment by brytsknguyen** [comment]
Hi,

To download the ground truth you can click on the figure under the ground truth collum in Section 1.Download.

![image](https://github.com/mcdviral/mcdviral.github.io/assets/13504903/be2e3b9d-c1d6-48f7-90aa-4a398224ebad)

That would lead you to the drive folder containing the whole trajectory ground truth

![image](https://github.com/mcdviral/mcdviral.github.io/assets/13504903/4be7f2f2-d125-48a5-a251-672d7a0f8c42)

**Comment by bumblebee15138** [comment]
It was my oversight that I didn't notice the relevant reminder. Thank you for your help.
