### ISSUE TITLE
Question about IMU-related parameters:

### ISSUE THREAD

**Issue by bumblebee15138** [mcdviral/mcdviral.github.io#2]
Hi,
I would like to ask:   where can I obtain the noise parameters and random walk parameters of IMUs in the dataset? 
Are these parameters included in the dataset, or are they not?

**Comment by brytsknguyen** [comment]
Hi,

The main IMUs (VN100 and VN200) have been precalibrated. Below are some reports from Kalibr I still keep.

[atv_calib_1imu_2cam_data-report-imucam.pdf](https://github.com/user-attachments/files/15821205/atv_calib_1imu_2cam_data-report-imucam.pdf)
[hhs_calib_data-report-imucam.pdf](https://github.com/user-attachments/files/15821187/hhs_calib_data-report-imucam.pdf)

These numbers are just for reference. I notice that the VN200 on the hhs may have a larger bias than the VN100 on the ATV.

You can find some examples on declaring the intrinsics of the IMU in my SLAM method SLICT here

https://github.com/brytsknguyen/slict/blob/d0772ab4e990050493f3a060deaae09a522b7df5/config/mcdviral_atv.yaml#L47
https://github.com/brytsknguyen/slict/blob/d0772ab4e990050493f3a060deaae09a522b7df5/config/mcdviral_hhs.yaml#L47

**Comment by bumblebee15138** [comment]
Thanks.
