### ISSUE TITLE
Request for Global PCD File with Labeled Point Cloud

### ISSUE THREAD

**Issue by Lkaho** [mcdviral/mcdviral.github.io#3]
Thank you for the work on this dataset.

I am working with labeled point cloud data and need a global point cloud map that retains these labels. Could you please provide the global point cloud map as a PCD file with the label data included?

Thank you!

**Comment by snakehaihai** [comment]
See red button called  Download here 

https://mcdviral.github.io/Groundtruth.html

![image](https://github.com/user-attachments/assets/bc04c8fb-0951-4aa6-b151-3e5efbf69306)

We will try to update as soon as possible. Mean while, if you are hurry, You may merge the scan with the ground truth pose to reconstruct the map. Then, based on the map transfer the label to a global map. 

#update

See 3 link below

KTH

https://entuedu-my.sharepoint.com/:u:/g/personal/shyuan_staff_main_ntu_edu_sg/EZO4KnKrbPZPnqNEj1XiP-8BafXFmEzi50QKFIhrDlPNew?e=lWH6eD

NTU

https://entuedu-my.sharepoint.com/:u:/g/personal/shyuan_staff_main_ntu_edu_sg/ET-ZUnEgpRhKl6d1y4sXQ2sBdfSzK1TxueeJ9Ntqavt2AQ?e=OpUBul

TUHH

https://entuedu-my.sharepoint.com/:u:/g/personal/shyuan_staff_main_ntu_edu_sg/EQ3RQ3AIQnpDmJqVs-yYG6oBBzs-GdRRc-bDz-f5T4dd3Q?e=Hel4jD

![image](https://github.com/user-attachments/assets/6aa93017-68e7-47b7-b887-d0b4b7c377ce)


Rgs
Shenghai Yuan
