### ISSUE TITLE
How to obtain annotated Lidar with corresponding pose files?

### ISSUE THREAD

**Issue by YHY138** [mcdviral/mcdviral.github.io#5]
Thank you for the excellent work your team has done. 
I have downloaded the Labelled Lidar data from the Annotated Lidar section of the link (https://mcdviral.github.io/AnnotatedLidar.html). However, I only received the point cloud (pcd) files and their labels, and not the corresponding pose files. Could you please clarify whether the pose files for the Annotated Lidar section have not been open-sourced yet, or if we need to extract the desired pcd and pose data ourselves from the Survey-grade prior map? 
Thanks in advance！

**Comment by brytsknguyen** [comment]
Hi @YHY138 YHY138, 

I have uploaded the poses of the pointclouds in each ground truth folder. Please check them and let me know if there is any issue.

![image](https://github.com/user-attachments/assets/cf2650fd-3dd3-4ec7-bd5f-5627c40a10b2)

**Comment by YHY138** [comment]
Thank you very much for your help

> Hi @YHY138 YHY138,
> 
> I have uploaded the poses of the pointclouds in each ground truth folder. Please check them and let me know if there is any issue.
> 
> ![image](https://private-user-images.githubusercontent.com/13504903/364311554-cf2650fd-3dd3-4ec7-bd5f-5627c40a10b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDc0MzUsIm5iZiI6MTcyNTcwNzEzNSwicGF0aCI6Ii8xMzUwNDkwMy8zNjQzMTE1NTQtY2YyNjUwZmQtM2RkMy00ZWM3LWJkNWYtNTYyN2M0MGExMGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDExMDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYmZhMmQ2OTFkOTIxZTM1ZmE4NTMxYzUyZjA4YWQ3NGU0YTJmMDIzYWQ4NTA4OWRkMWZiOTU3YjAwNTFlZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eMN6MdKWxhVhXrWzqt0S0E_jPkMTteFo_HIS-I8HGFU)
