### ISSUE TITLE
How to use evo to evaluate the pose I get with the pose_inW.csv?

### ISSUE THREAD

**Issue by HxCa1** [mcdviral/mcdviral.github.io#8]
Hello, thank you for the great work.
As the title, I have encountered the following problem:
evo_ape tum ntuday01.tum ../pose/ntu_day_01_pose_inW.csv -va 
--------------------------------------------------------------------------------
Loaded 3136 stamps and poses from: ntuday01.tum
[ERROR] TUM trajectory files must have 8 entries per row and no trailing delimiter at the end of the rows (space)

After I delete the top lines "num t x y z qx qy qz qw" and the num row，I found this:
found no matching timestamps between ntuday01.tum and ../pose/ntuday01.tum with max. time diff 0.01 (s) and time offset 0.0 (s)

If you can offer some suggestions, I would greatly appreciate it.

**Comment by snakehaihai** [comment]
- -0 

It says clearly. it must have 8 entry.  TUM expects:  timestamp x y z q_x q_y q_z q_w

what you have is  num t x y z qx qy qz qw

1num 2t 3x 4y 5z 6qx 7qy 8qz 9qw


I think the answer is pretty clear. Delete First column
